# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-19 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_tile', models.CharField(max_length=200)),
                ('check_des', models.CharField(max_length=500)),
                ('img_path', models.CharField(max_length=200)),
                ('txt_filed', models.CharField(max_length=1000)),
                ('cate_list', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('password_confirmation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='checkmodel',
            name='check_imgid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.UploadModel'),
        ),
        migrations.AddField(
            model_name='checkmodel',
            name='check_userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.RegisterModel'),
        ),
    ]
