# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-19 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='userid',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
