# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-25 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_registermodel_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Html_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htmlfile', models.FileField(upload_to='')),
            ],
        ),
    ]
